version: '3.8'

services:
  postgres-db:
    image: postgres:11.20-bullseye
    container_name: postgres-db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=main-db
    healthcheck:
      test: "exit 0"

  affiliate-server:
    container_name: affiliate-app
    build:
      context: ./
      dockerfile: server.Dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:123456789@postgres-db:5432/main-db
    ports:
      - 3000:3000